name: Cypress Tests Poc 2

on: 
    #push

    workflow_dispatch:
    

jobs:

  call-workflow:
    uses: maksonrochati/cypress-poc-1/.github/workflows/qaops.yml@main
  
  #cypress-run:
    #runs-on: ubuntu-22.04
    #steps:
      #- name: Checkout v4
       # uses: actions/checkout@v4

      #- name: Checkout v2
       # uses: actions/checkout@v2
       
          
     # - name: Cypress run
       # uses: cypress-io/github-action@v6
