name: Cypress Tests Poc 2

on: 
    #push

    workflow_dispatch:
    workflow_call:
        inputs:
            config-path:
                required: true
                type: string
    

jobs:
  cypress-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout v4
        uses: actions/checkout@v4

 # call-workflow:
    #uses: maksonrochati/cypress-poc-1/.github/workflows/qaops.yml@poc
  

      #- name: Checkout v2
       # uses: actions/checkout@v2
       
          
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
            command: npx cypress run
