name: Cypress Tests Poc 2

on: 
    #push

    workflow_dispatch:
    workflow_call:
        inputs:
          config-path:
            required: true
            type: string
      
        
    

jobs:
  cypress-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout v4
        uses: actions/checkout@v4
    

 # call-workflow:
    #uses: maksonrochati/cypress-poc-1/.github/workflows/qaops.yml@poc
  

     # - name: Npm install
      #  run: npm install

      #- name: Cypress install
        #run: npm install cypress

      #- name: Exec Spec Poc 2
        #run: npx cypress run --spec "cypress/e2e/teste/todo.cy.js"
       
          
      - name: Cypress run poc 2
        uses: cypress-io/github-action@v4
        with:
            project: ./teste
        
       
