name: Cypress Tests Poc 2

on: 
    #push

    workflow_dispatch:
    workflow_call:

jobs:

  call-workflow-1-in-local-repo:
    uses: maksonrochati/cypress-poc-2/.github/actions/workflows/qaops.yaml
  
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout v4
        uses: actions/checkout@v4

      - name: Checkout v2
        uses: actions/checkout@v2
        with:
            repository: maksonrochati/cypress-poc-1
            #token: ${{ secrets.GH_TOKEN }}
            path: .github/actions/workflows/qaops.yaml
          
      - name: Cypress run
        uses: cypress-io/github-action@v6
